### ISSUE TITLE
Kontrolle Aufgabe 03

### ISSUE THREAD

**Issue by MelvinBusch** [Jonas915/EIA2#1]
1. AD's könnten etwas ausführlicher sein.
2. Aufgabenordner auf dem Repository bitte aufräumen. Also z.B. Unterordner wie `ts`, `konzept`, `styles` o.ä. anlegen.
3. Klickt man nach dem legen einer Karte auf sortieren, dann gibt es einen Fehler und das Spiel funktioniert nicht mehr richtig. Hier nochmal auf Fehlersuche gehen!
4. Funktions- und Variablen Namen könnten etwas aussagekräftiger sein. Man weiß oft nicht was damit gemeint ist.

_15.04 | 00:22 (mb)_

**Comment by Jonas915** [comment]
done.

**Comment by MelvinBusch** [comment]
Verteidigt (mb)
